import type { DocumentPage } from '../../types'
import { callout, diagram, list, page, table, text } from '../canvaPracticumShared'

type Topic = {
  number: number
  title: string
  subtitle: string
  opening: string
  why: string
  model: Array<[string, string, 'slate' | 'cyan' | 'blue' | 'violet' | 'emerald' | 'amber' | 'rose']>
  schemaTitle: string
  schema: Array<[string, string, 'slate' | 'cyan' | 'blue' | 'violet' | 'emerald' | 'amber' | 'rose']>
  schemaFooter: string
  compareTitle: string
  compareHeaders: string[]
  compareRows: string[][]
  walkthroughTitle: string
  walkthroughText: string
  walkthroughPoints: string[]
  principleTitle: string
  principles: string[]
  developmentTitle: string
  development: string
  pitfalls: string[]
  prompt: string
  caseTitle: string
  caseText: string
  casePoints: string[]
  deepTitle: string
  deepText: string
  deepPoints: string[]
  evidenceTitle: string
  evidenceText: string
  evidencePoints: string[]
}

const topics: Topic[] = [
  {
    number: 1,
    title: 'Identitet, autentikacija i RBAC',
    subtitle: 'Ko pristupa sistemu i zašto identitet prethodi svakoj odluci',
    opening: 'Bezbednost počinje razdvajanjem identiteta, prijave i ovlašćenja. Sistem najpre treba da pouzdano prepozna subjekat, zatim da proceni njegov aktuelni status, a tek potom da proveri šta taj subjekat sme da uradi. Kada se ti koraci pomešaju, greške se lako sakriju iza jedne uspešne prijave.',
    why: 'RBAC je važan zato što prava ne dodeljuje proizvoljno svakom nalogu. Uloge izražavaju odgovornosti u organizaciji, pa tim može razumljivo da upravlja pristupom, da ga pregleda i da ga ukine kada više nije potreban.',
    model: [['Identitet', 'subjekat sa životnim ciklusom', 'slate'], ['Autentikacija', 'potvrda ko je subjekat', 'cyan'], ['Uloga', 'poslovna odgovornost', 'blue'], ['Dozvola', 'konkretna dopuštena radnja', 'emerald']],
    schemaTitle: 'Šema odluke o pristupu',
    schema: [['Zahtev', 'ko i šta traži', 'slate'], ['Potvrda identiteta', 'da li je subjekat aktivan', 'cyan'], ['Provera dozvole', 'uloga i opseg', 'blue'], ['Audit ishod', 'dopušteno ili odbijeno', 'emerald']],
    schemaFooter: 'Prijava je samo jedna faza. Pravo pristupa nastaje tek kada sistem proveri ceo kontekst.',
    compareTitle: 'Poređenje osnovnih pojmova identiteta',
    compareHeaders: ['Pojam', 'Pitanje na koje odgovara', 'Tipična greška'],
    compareRows: [['Identitet', 'Ko je subjekat?', 'Mešanje osobe i tehničkog naloga.'], ['Autentikacija', 'Da li je tvrdnja o identitetu potvrđena?', 'Uspešna prijava se tumači kao široko ovlašćenje.'], ['Autorizacija', 'Da li je radnja dopuštena?', 'Provera se radi samo u korisničkom interfejsu.'], ['Sesija', 'U kom privremenom kontekstu pristup važi?', 'Token se tretira kao trajno pravo.']],
    walkthroughTitle: 'Tok razmišljanja pri odluci o pristupu',
    walkthroughText: 'Kada sistem primi zahtev, korisno je posmatrati odluku kao niz pitanja, a ne kao jednu metodu koja vraća da ili ne. Svako pitanje smanjuje skup mogućih grešaka i ostavlja jasan trag za kasniji pregled.',
    walkthroughPoints: ['Da li je subjekat poznat i aktivan?', 'Da li je zahtevana radnja definisana kao dozvola?', 'Da li uloga i opseg daju to pravo baš u ovom trenutku?', 'Koji audit zapis opisuje uspeh ili odbijanje?'],
    principleTitle: 'Mentalni model pristupa',
    principles: ['Uspešna prijava potvrđuje identitet, ali sama po sebi ne daje pravo na resurs.', 'Uloga treba da bude čitljiva poslovna odgovornost, a dozvola mala i proverljiva radnja.', 'Promena statusa ili uloge menja pristup odmah, bez oslanjanja na zastarelu pretpostavku klijenta.'],
    developmentTitle: 'Kako se ova tema vidi u razvoju',
    development: 'Dizajn počinje pitanjima ko su akteri, koje odgovornosti imaju i nad kojim opsegom rade. Server donosi konačnu odluku; interfejs samo pomaže korisniku da ne bira radnje koje verovatno neće proći.',
    pitfalls: ['Mešanje autentikacije i autorizacije u jednu proveru.', 'Davanje široke uloge zato što je brže od oblikovanja jedne dozvole.', 'Oslanjanje na sakriveno dugme kao na bezbednosnu kontrolu.'],
    prompt: 'Za jednu administrativnu radnju objasnite razliku između identiteta, uloge, dozvole i opsega u kome dozvola važi.',
    caseTitle: 'Primer: operator dobija novu odgovornost',
    caseText: 'Operater je do juče pregledao izveštaje, a danas privremeno pomaže timu koji odobrava promene na osetljivim resursima. Najjednostavnije rešenje deluje kao dodela administratorske uloge. Međutim, ta odluka često otvara mnogo više radnji nego što je stvarno potrebno, a kasnije je teško utvrditi koje pravo je bilo opravdano i kada treba da nestane.',
    casePoints: ['Prvo se određuje konkretna radnja koju operator treba da izvrši, a ne naziv najšire postojeće uloge.', 'Zatim se proverava opseg: da li pravo važi za ceo sistem, jedan domen ili samo ograničeno vreme.', 'Na kraju se definiše revizija ili istek, kako privremena potreba ne bi ostala trajna privilegija.'],
    deepTitle: 'Dizajnerska odluka: uloga nije dozvola',
    deepText: 'Uloga je način da organizacija grupiše odgovornosti, dok dozvola izražava najmanju radnju koju sistem štiti. To razdvajanje deluje kao dodatni posao na početku, ali smanjuje cenu svake kasnije promene. Kada se doda nova radnja, tim ne mora da izmišlja novu kombinaciju korisnika i izuzetaka, već procenjuje kojoj odgovornosti pripada i nad kojim opsegom važi.',
    deepPoints: ['Uloge treba imenovati po odgovornosti, ne po tehničkom sloju aplikacije.', 'Dozvola treba da opisuje radnju i resurs dovoljno precizno da može da se proveri.', 'Efektivna prava nastaju iz uloge, opsega i aktuelnog statusa, a ne iz jednog statičkog polja korisnika.'],
    evidenceTitle: 'Kako znamo da model pristupa radi',
    evidenceText: 'Najkorisniji dokaz nije samo uspešna prijava. Potrebno je pokazati i da sistem odbija radnju kada izostane jedna potrebna činjenica: aktivan identitet, odgovarajuća dozvola ili ispravan opseg. Takvi negativni slučajevi štite model od slučajnog širenja prava kroz kasnije izmene.',
    evidencePoints: ['Testovi porede očekivano dopuštenu i odbijenu radnju nad istim tipom resursa.', 'Audit zapis čuva ko je pokušao radnju, šta je traženo i kakav je ishod.', 'Pregled prava treba da objasni zašto korisnik ima pristup, a ne samo da prikaže naziv njegove uloge.'],
  },
  {
    number: 2,
    title: 'Autorizacija nad resursom i klasifikacija podataka',
    subtitle: 'Zašto poznavanje adrese resursa ne znači pravo pristupa',
    opening: 'Autorizacija ima smisla tek kada je vezana za konkretan resurs i njegov kontekst. Korisnik može imati legitimnu ulogu, a ipak ne sme da čita, menja ili deli baš taj zapis. Zato se odluka ne završava proverom tipa endpointa ili naziva uloge.',
    why: 'Klasifikacija podataka daje isti jezik vlasnicima, razvoju i operacijama. Kada sistem zna koliko je podatak osetljiv, može da primeni odgovarajući pristup, prikaz, čuvanje i evidenciju bez oslanjanja na nečije sećanje.',
    model: [['Subjekat', 'ko traži radnju', 'slate'], ['Resurs', 'nad čim se radi', 'cyan'], ['Kontekst', 'vlasništvo i namena', 'blue'], ['Odluka', 'dozvoli ili odbij', 'emerald']],
    schemaTitle: 'Šema zaštite jednog resursa',
    schema: [['Resurs', 'vlasnik i klasifikacija', 'slate'], ['Radnja', 'čitanje, izmena ili izvoz', 'cyan'], ['Serverska provera', 'subjekat, odnos i pravilo', 'blue'], ['Bezbedan ishod', 'podaci ili kontrolisano odbijanje', 'emerald']],
    schemaFooter: 'Identifikator u adresi ne predstavlja pravo pristupa. Odnos subjekta prema resursu proverava se na serveru.',
    compareTitle: 'Nivoi provere pristupa',
    compareHeaders: ['Nivo', 'Šta proverava', 'Zašto nije dovoljan sam'],
    compareRows: [['Prijava', 'Identitet subjekta.', 'Ne govori šta subjekat sme da uradi.'], ['Uloga', 'Opšti skup odgovornosti.', 'Ne zna odnos prema konkretnom zapisu.'], ['Resurs', 'Vlasništvo, pripadnost i klasifikaciju.', 'Mora se kombinovati sa radnjom i politikom.'], ['Kontekst', 'Vreme, stanje i poslovno opravdanje.', 'Može promeniti zaključak za istu ulogu.']],
    walkthroughTitle: 'Životni ciklus podatka',
    walkthroughText: 'Zaštita podataka ne završava se u trenutku čitanja. Isti podatak prolazi kroz kreiranje, upotrebu, deljenje, čuvanje i uklanjanje. Svaka faza postavlja drugo pitanje o dozvoljenom pristupu i potrebnom tragu.',
    walkthroughPoints: ['Pri kreiranju se određuju vlasnik i klasifikacija.', 'Pri korišćenju se proverava svrha i opseg pristupa.', 'Pri deljenju se proverava granica poverenja i minimalni skup podataka.', 'Pri čuvanju i uklanjanju važe retention i audit pravila.'],
    principleTitle: 'Odluka mora imati kontekst',
    principles: ['Provera prava uključuje subjekt, radnju, resurs i njegovu pripadnost.', 'Odbijanje ne treba da otkriva sadržaj niti postojanje tuđeg osetljivog resursa.', 'Klasifikacija nije etiketa za dokumentaciju, već ulaz u pravila rukovanja podacima.'],
    developmentTitle: 'Kako se ova tema vidi u razvoju',
    development: 'Za svaku značajnu operaciju tim formuliše i pozitivan i negativan scenario. Negativan scenario proverava da pravilno prijavljen korisnik ne može da zaobiđe vlasništvo promenom identifikatora ili pozivom API-ja van interfejsa.',
    pitfalls: ['Provera uloge bez provere odnosa prema konkretnom resursu.', 'Filtriranje liste u klijentu bez iste provere na serveru.', 'Snižavanje klasifikacije bez obrazloženja i traga promene.'],
    prompt: 'Koji resurs nosi rizik horizontalnog pristupa i koje informacije odluka mora da uzme u obzir?',
    caseTitle: 'Primer: ispravna uloga, pogrešan zapis',
    caseText: 'Dva člana tima imaju istu ulogu i obojica mogu da pregledaju zahteve. Jedan menja identifikator u adresi zahteva i dolazi do tuđeg zapisa. Sistem koji proverava samo ulogu smatra zahtev dozvoljenim, iako se promenio najvažniji deo konteksta: odnos korisnika prema konkretnom resursu.',
    casePoints: ['Odluka uključuje identitet, traženu radnju, resurs i pripadnost resursa odgovarajućem domenu ili vlasniku.', 'Isti princip važi za API poziv, izvoz podataka i pozadinsku obradu, ne samo za ekran koji korisnik vidi.', 'Odgovor na odbijeni pristup treba da bude koristan klijentu, ali ne sme da otkrije podatke o zaštićenom zapisu.'],
    deepTitle: 'Dizajnerska odluka: podatak nosi obaveze',
    deepText: 'Klasifikacija ne govori samo koliko je podatak važan. Ona utiče na način prikaza, izvoz, deljenje, čuvanje i brisanje. Kada te posledice nisu jasno vezane za klasifikaciju, svaki novi ekran ili integracija mora ponovo da pogađa kako treba rukovati informacijom.',
    deepPoints: ['Klasifikacija ima poslovno značenje koje svi članovi tima tumače na isti način.', 'Pravila za prikaz i izvoz treba da budu stroža kada posledice greške rastu.', 'Vlasnik podatka odgovara za opravdanost promene klasifikacije, a sistem čuva trag te promene.'],
    evidenceTitle: 'Kako znamo da je autorizacija potpuna',
    evidenceText: 'Pristup treba proveriti kroz stvarnu granicu sistema, a ne samo kroz korisnički interfejs. To znači da direktan API zahtev, pozadinski proces i izvoz ne mogu preskočiti isto pravilo. Negativni testovi zato nisu dodatak posle implementacije, već najjasniji opis granice pristupa.',
    evidencePoints: ['Sistem jednako štiti resurs kada se zahtev pošalje van standardnog ekrana.', 'Odbijeni zahtev ne vraća detalje koji pomažu da se mapiraju tuđi podaci.', 'Promena klasifikacije i promena vlasništva ostavljaju dovoljno traga za kasniji pregled.'],
  },
  {
    number: 3,
    title: 'Politike, konfiguracija i bezbednosna vidljivost',
    subtitle: 'Eksplicitna pravila umesto bezbednosti skrivene u kodu',
    opening: 'Bezbednosna pravila postaju pouzdana tek kada su vidljiva, verzionisana i proverljiva. Pravilo rasuto kroz nekoliko metoda nije lako objasniti, pregledati niti promeniti bez neželjenih posledica. Politika zato predstavlja dogovoreno pravilo, a konfiguracija njegovu primenu u konkretnom okruženju.',
    why: 'Vidljivost ne služi samo reagovanju na incident. Ona omogućava timu da razume odluku sistema, prati odstupanje od očekivanog stanja i poveže događaje kroz različite slojeve aplikacije.',
    model: [['Politika', 'šta organizacija očekuje', 'slate'], ['Konfiguracija', 'kako se pravilo primenjuje', 'cyan'], ['Kontrola', 'mehanizam zaštite', 'blue'], ['Dokaz', 'log, metrika ili test', 'emerald']],
    schemaTitle: 'Šema od pravila do dokaza',
    schema: [['Politika', 'opisana namera i opseg', 'slate'], ['Konfiguracija', 'važeće vrednosti i pragovi', 'cyan'], ['Kontrola', 'sprovodi odluku', 'blue'], ['Dokaz', 'pokazuje stvarni ishod', 'emerald']],
    schemaFooter: 'Pravilo može biti dobro napisano, a kontrola ipak neefektivna. Dokaz povezuje očekivanje sa realnim ponašanjem.',
    compareTitle: 'Politika, procedura i kontrola',
    compareHeaders: ['Element', 'Uloga', 'Primer dokaza'],
    compareRows: [['Politika', 'Određuje pravilo i cilj zaštite.', 'Verzionisan tekst sa vlasnikom.'], ['Procedura', 'Opisuje kako ljudi ili sistem sprovode pravilo.', 'Pregled koraka ili automatizovani tok.'], ['Kontrola', 'Sprečava, otkriva ili ograničava rizik.', 'Test, log ili rezultat provere.'], ['Metrika', 'Pokazuje trend ili odstupanje.', 'Definisan prag i izvor podataka.']],
    walkthroughTitle: 'Kako se bira bezbednosna metrika',
    walkthroughText: 'Metrika je korisna samo ako vodi ka odluci. Zato se ne počinje brojem, već pitanjem koje operater ili vlasnik sistema mora da reši. Zatim se bira izvor, period posmatranja i prag pri kome je potrebna akcija.',
    walkthroughPoints: ['Koje ponašanje želimo da razumemo ili ograničimo?', 'Koji događaji pouzdano predstavljaju to ponašanje?', 'Ko je vlasnik praga i šta radi kada se prag pređe?', 'Kako razlikujemo normalnu promenu rada od bezbednosnog odstupanja?'],
    principleTitle: 'Pravilo bez dokaza je samo namera',
    principles: ['Nova verzija politike ne briše razlog zbog kog je stara odluka nekada bila ispravna.', 'Konfiguraciona vrednost ima vlasnika, značenje i očekivani opseg.', 'Korelacioni identifikator povezuje jedan bezbednosni tok kroz slojeve sistema.'],
    developmentTitle: 'Kako se ova tema vidi u razvoju',
    development: 'Tim bira nekoliko ključnih odluka koje mora moći da objasni iz loga i testa. To nisu svi događaji sistema, već oni čiji bi nejasan ishod otežao istragu, pregled pristupa ili korekciju konfiguracije.',
    pitfalls: ['Uređivanje objavljene politike na mestu bez istorije.', 'Tajne u konfiguracionim datotekama ili logovima.', 'Metrika bez jasnog pitanja na koje treba da odgovori.'],
    prompt: 'Koje bezbednosno pravilo bi trebalo da bude zaseban, čitljiv artefakt u vašoj celini i koji dokaz pokazuje da radi?',
    caseTitle: 'Primer: promena pravila bez gubitka istorije',
    caseText: 'Tim pooštrava pravilo za pristup administrativnom interfejsu. Ako staro pravilo samo prepiše novim, kasnije ne može da objasni zašto je raniji pristup bio dozvoljen niti da rekonstruiše koje je očekivanje tada važilo. Verzionisanje ne služi birokratiji, već očuvanju smisla istorijskih odluka.',
    casePoints: ['Politika opisuje nameru i važenje, dok konfiguracija čuva vrednosti kojima se ta namera primenjuje u okruženju.', 'Svaka promena koja utiče na odluku ima vlasnika, datum i jasan razlog.', 'Log, metrika ili test daju dokaz da sistem radi prema aktivnom pravilu, a ne samo da je pravilo zapisano.'],
    deepTitle: 'Dizajnerska odluka: pravilo mora imati granice',
    deepText: 'Politika postaje korisna kada je dovoljno precizna da ljudi donose dosledne odluke, a dovoljno čitljiva da se može objasniti bez čitanja izvornog koda. Dobro pravilo navodi na šta se odnosi, ko je vlasnik, kada važi i šta se dešava ako se pravila sukobe.',
    deepPoints: ['Konflikt politika rešava se unapred dogovorenim pravilom, često restriktivnijom odlukom.', 'Konfiguracija ne menja smisao politike bez vidljivog procesa odobravanja.', 'Bezbednosna kontrola ima vlasnika i očekivani dokaz, inače niko ne prati da li je prestala da radi.'],
    evidenceTitle: 'Vidljivost kao sposobnost tima',
    evidenceText: 'Observability ne znači čuvanje svakog detalja zauvek. Znači da se za važnu odluku može pronaći dovoljno konteksta: gde je nastala, kroz koje slojeve je prošla i zašto je završila uspehom ili odbijanjem. Korelacioni identifikator daje zajedničku nit tom objašnjenju.',
    evidencePoints: ['Logovi razlikuju tehnički trag od bezbednosno značajnog audit zapisa.', 'Metrika ima ime, vlasnika i jasno pitanje koje pomaže da se odgovori.', 'Tajne, tokeni i nepotrebni lični podaci ne pripadaju ni logu ni metričkoj oznaci.'],
  },
  {
    number: 4,
    title: 'Imovina, granice poverenja i threat modeling',
    subtitle: 'Razumevanje onoga što štitimo pre izbora kontrole',
    opening: 'Dobra bezbednosna odluka ne polazi od liste poznatih rešenja, već od vredne imovine, toka podataka i granica poverenja. Tek tada tim može da prepozna šta bi moglo poći po zlu i koja kontrola ima smisla za konkretan rizik.',
    why: 'Threat modeling povezuje tehničku strukturu sistema sa poslovnim posledicama. Pomaže timu da ranije uoči pogrešne pretpostavke, umesto da bezbednost dodaje nakon što se arhitektura već učvrsti.',
    model: [['Imovina', 'vredan podatak ili servis', 'slate'], ['Tok podataka', 'kretanje informacije', 'cyan'], ['Granica poverenja', 'promena pretpostavki', 'amber'], ['Pretnja i kontrola', 'rizik i odgovor', 'emerald']],
    schemaTitle: 'Šema threat modela',
    schema: [['Imovina', 'šta štitimo', 'slate'], ['Tok i granica', 'gde se menja poverenje', 'cyan'], ['Scenario', 'šta može poći po zlu', 'amber'], ['Kontrola i dokaz', 'kako umanjujemo rizik', 'emerald']],
    schemaFooter: 'Pretnja dobija smisao tek kada se veže za konkretnu imovinu, tok i posledicu.',
    compareTitle: 'Imovina, ranjivost i pretnja',
    compareHeaders: ['Pojam', 'Značenje', 'Pitanje za analizu'],
    compareRows: [['Imovina', 'Ono čija vrednost zahteva zaštitu.', 'Šta gubimo ako je ugrožena?'], ['Ranjivost', 'Slabost koju je moguće iskoristiti.', 'Gde sistem nema dovoljnu zaštitu?'], ['Pretnja', 'Mogući uzrok neželjenog ishoda.', 'Ko ili šta može aktivirati slabost?'], ['Rizik', 'Kombinacija verovatnoće i posledice.', 'Šta prvo treba umanjiti?']],
    walkthroughTitle: 'Čitanje arhitektonske skice kroz bezbednost',
    walkthroughText: 'Arhitektonska skica dobija bezbednosnu vrednost kada se preko komponenti ucrtaju podaci, identiteti i granice poverenja. Nije potrebno crtati svaku klasu. Dovoljno je pokazati delove kroz koje prolazi vredna informacija i odluke koje menjaju njen status.',
    walkthroughPoints: ['Označiti ulaze koje kontroliše korisnik ili spoljašnji servis.', 'Označiti mesto gde se identitet ili dozvola ponovo proveravaju.', 'Označiti skladišta, ključeve i integracije koje menjaju posledicu incidenta.', 'Uz svaku granicu zapisati jednu realnu pretpostavku koja može biti pogrešna.'],
    principleTitle: 'Model pre kontrole',
    principles: ['Imovina ima vlasnika, značaj i životni ciklus.', 'Spoljna komponenta ne dobija poverenje samo zato što je integrisana.', 'Pretnja postaje korisna kada vodi do zahteva, kontrole i načina provere.'],
    developmentTitle: 'Kako se ova tema vidi u razvoju',
    development: 'Arhitekturni crtež postaje radni alat kada uz svaku važnu granicu navede podatke, aktere i pretpostavke. Tim zatim bira mali broj realnih misuse scenarija i proverava ih testom ili pregledom dizajna.',
    pitfalls: ['Inventar koji postoji samo radi evidencije, bez vlasništva i značaja.', 'Opšti katalog pretnji koji nije povezan sa stvarnim sistemom.', 'Kontrola izabrana pre razumevanja rizika koji treba da smanji.'],
    prompt: 'Nacrtajte jedan tok osetljivog podatka i označite mesto na kome se pretpostavka o poverenju menja.',
    caseTitle: 'Primer: izvoz iz internog sistema',
    caseText: 'Interni servis priprema izvoz osetljivih podataka za drugi sistem. Tim ga doživljava kao bezbedan jer je servis „unutra“, ali sam prelazak podataka u drugi sistem menja pretpostavke. Potrebno je znati koji podatak putuje, ko prima podatak, šta može poći po zlu i kako sistem sprečava ili bar otkriva neželjen ishod.',
    casePoints: ['Imovina se ne svodi na bazu podataka: uključuje naloge, ključeve, servisne identitete, konfiguraciju i poslovne zapise.', 'Granica poverenja može biti API poziv, red poruka, administrativni interfejs ili izvoz u datoteku.', 'Dobar threat model bira nekoliko realnih scenarija i uz svaki navodi kontrolu i način provere.'],
    deepTitle: 'Dizajnerska odluka: prvo model, zatim alat',
    deepText: 'Bezbednosni alat ne rešava problem samim uvođenjem. Ako tim ne zna koju imovinu alat štiti, koju granicu nadgleda i koji scenario treba da otkrije, rezultat će biti mnoštvo signala bez jasnog prioriteta. Threat model služi kao mapa po kojoj se bira kontrola i procenjuje njena vrednost.',
    deepPoints: ['Kritičnost imovine određuje koliko brzo se reaguje i koliko je dokaza potrebno.', 'Tok podataka otkriva mesta na kojima informacija može biti izmenjena, izgubljena ili pogrešno izložena.', 'Pretnja dobija prioritet prema uticaju, verovatnoći i realnim postojećim kontrolama.'],
    evidenceTitle: 'Kako threat model ostaje živ dokument',
    evidenceText: 'Model pretnji nije dokument koji se napiše jednom na početku semestra. Menja se kada se doda novi ulaz, integracija, način čuvanja podataka ili privilegovana radnja. Svaka veća arhitektonska promena je prilika da se proveri da li su stare pretpostavke i dalje tačne.',
    evidencePoints: ['Dijagram se ažurira kada tok podataka ili granica poverenja stvarno promeni ponašanje sistema.', 'Za odabrani scenario postoji veza do kontrole, testa ili pregleda koji ga proverava.', 'Preostali rizik se zapisuje jasno, umesto da se pretvara da nijedna pretnja više ne postoji.'],
  },
  {
    number: 5,
    title: 'MFA, sesije, servisi i tajne',
    subtitle: 'Kontrola pristupa kroz vreme, a ne samo u trenutku prijave',
    opening: 'Identitet nije trajno dokazan jednom prijavom. Rizik radnje, trajanje sesije, vrsta uređaja i promena privilegija utiču na to koliko je dodatna potvrda potrebna. Operativna bezbednost zato prati pristup i nakon početne autentikacije.',
    why: 'Višefaktorska potvrda i vremenski ograničene privilegije smanjuju posledice ukradenog kredencijala. Upravljanje tajnama štiti veze među servisima, gde nepažnja često ostane skrivena jer nema korisničkog ekrana.',
    model: [['Prijava', 'početna potvrda identiteta', 'slate'], ['Sesija', 'privremeni kontekst pristupa', 'cyan'], ['Dodatna potvrda', 'za rizičnu radnju', 'violet'], ['Istek ili opoziv', 'prekid važenja pristupa', 'emerald']],
    schemaTitle: 'Šema životnog ciklusa poverenja',
    schema: [['Početna prijava', 'osnovni nivo poverenja', 'slate'], ['Aktivna sesija', 'vremenski ograničena', 'cyan'], ['Rizična radnja', 'step-up ili odbijanje', 'violet'], ['Opoziv ili istek', 'pristup prestaje da važi', 'emerald']],
    schemaFooter: 'Poverenje se ne čuva zauvek. Sistem ga obnavlja ili opoziva kada se promeni rizik.',
    compareTitle: 'Različite vrste identiteta',
    compareHeaders: ['Identitet', 'Namena', 'Poseban rizik'],
    compareRows: [['Ljudski korisnik', 'Interaktivne radnje i odgovornost.', 'Krađa kredencijala ili preširoka uloga.'], ['Servisni nalog', 'Komunikacija među komponentama.', 'Tajna bez roka ili prevelik opseg.'], ['Privremeni pristup', 'Kratka rizična intervencija.', 'Pravo ostane aktivno nakon potrebe.'], ['Administratorski nalog', 'Izmene sa velikim uticajem.', 'Nedostatak dodatne potvrde i audita.']],
    walkthroughTitle: 'Od tajne do bezbedne upotrebe',
    walkthroughText: 'Bezbedno upravljanje tajnom počinje pre njenog prvog korišćenja. Potrebno je znati vlasnika, svrhu, komponentu koja je koristi i način rotacije. Sama vrednost tajne treba da ostane van koda, ekrana i zapisa koji nisu za to namenjeni.',
    walkthroughPoints: ['Tajna se izdaje samo identitetu koji joj je stvarno potreban.', 'Sistem prati istek i planira rotaciju pre prekida rada.', 'Logovi beleže upotrebu i neuspeh bez prikazivanja vrednosti tajne.', 'Opoziv ograničava posledicu sumnje da je tajna kompromitovana.'],
    principleTitle: 'Pristup ima rok i kontekst',
    principles: ['Sesija može izgubiti važnost pre planiranog isteka.', 'Dodatna potvrda prati rizik radnje, ne samo tip korisnika.', 'Servisni identitet ima mali, jasno opravdan opseg, kao i ljudski identitet.'],
    developmentTitle: 'Kako se ova tema vidi u razvoju',
    development: 'Razvojni tim unapred određuje koje situacije menjaju nivo poverenja: promena privilegije, pristup osetljivom podatku ili sumnjiva prijava. Tajne se referenciraju iz bezbednog izvora i nikada se ne prenose kroz kod, testne ispise ili istoriju repozitorijuma.',
    pitfalls: ['Token tretiran kao večna dozvola.', 'Administratorska prava dodeljena bez roka i pregleda.', 'Jedna široka tajna deljena među više nezavisnih servisa.'],
    prompt: 'Koja radnja zaslužuje dodatnu potvrdu identiteta i koji događaj bi trebalo da opozove postojeću sesiju?',
    caseTitle: 'Primer: sesija posle promene privilegije',
    caseText: 'Korisnik se prijavio ujutru, a kasnije tokom dana dobija viši nivo pristupa. Ako sistem ne preispita postojeću sesiju, korisnik može izvršiti rizičnu radnju bez dodatne potvrde koja bi bila potrebna da se prijavljuje u tom trenutku. Obrnuto, oduzeta privilegija mora zaista da prestane da važi, a ne da čeka kraj dugotrajne sesije.',
    casePoints: ['Sesija je privremeni dokaz konteksta, ne trajna potvrda poverenja.', 'Step-up autentikacija ima smisla kada se rizik radnje promeni, a ne kao proizvoljna prepreka za sve korisnike.', 'Servisni nalog dobija isti tretman kao korisnik: najmanji potreban opseg, rok važenja i kontrolisanu rotaciju tajne.'],
    deepTitle: 'Dizajnerska odluka: poverenje se obnavlja',
    deepText: 'Sesija olakšava rad korisniku, ali njen komfor ne sme postati trajno poverenje. Sistem mora znati kada se okolnosti menjaju dovoljno da prethodna potvrda više nije dovoljna. To mogu biti promena privilegije, neobičan uređaj, rizična radnja ili signal da je nalog ugrožen.',
    deepPoints: ['Istek ograničava trajanje poverenja čak i kada nema vidljivog incidenta.', 'Opoziv reaguje na konkretnu promenu rizika i ne čeka da sesija prirodno nestane.', 'Dodatni faktor dokazuje prisustvo ili posedovanje nezavisnog sredstva, a ne ponavlja samo istu lozinku.'],
    evidenceTitle: 'Tajne kao deo arhitekture',
    evidenceText: 'Tajna nije konfiguraciona vrednost kao svaka druga. Njeno izlaganje može dati pristup bez vidljivog korisničkog ekrana, naročito između servisa. Zato razvojni proces definiše odakle tajna dolazi, ko je koristi, kada se rotira i kako se proverava da nije slučajno završila u repozitorijumu ili logu.',
    evidencePoints: ['Svaki servisni identitet ima svrhu i najmanji potreban opseg.', 'Rotacija se planira pre isteka, umesto da se čeka prekid rada.', 'Testovi proveravaju ponašanje pri opozivu ili isteku bez prikazivanja stvarnih vrednosti tajne.'],
  },
  {
    number: 6,
    title: 'Detekcija, incident i ranjivosti',
    subtitle: 'Od signala ka proverljivoj i smirenoj reakciji',
    opening: 'Bezbednosni događaj nije automatski incident. Sistem najpre prepoznaje signal, zatim ga stavlja u kontekst i tek onda određuje da li je potrebna reakcija. Takav tok sprečava i ignorisanje problema i nepotrebno alarmiranje zbog svakog odstupanja.',
    why: 'Upravljanje incidentom daje strukturu trenutku kada je najlakše izgubiti kontekst. Ranjivost postaje rešiv problem kada je povezana sa imovinom, prioritetom, vlasnikom i dokazom da je korekcija proverena.',
    model: [['Signal', 'uočeno odstupanje', 'slate'], ['Triage', 'provera konteksta i uticaja', 'amber'], ['Incident', 'koordinisana reakcija', 'rose'], ['Učenje', 'korekcija i prevencija', 'emerald']],
    schemaTitle: 'Šema odgovora na bezbednosni događaj',
    schema: [['Događaj', 'signal iz sistema', 'slate'], ['Triage', 'kontekst i prioritet', 'amber'], ['Reakcija', 'incident ili kontrolisano zatvaranje', 'rose'], ['Poboljšanje', 'novi dokaz i manji rizik', 'emerald']],
    schemaFooter: 'Nije svaki signal incident, ali svaki značajan ishod ostavlja znanje korisno za sledeću odluku.',
    compareTitle: 'Signal, alert i incident',
    compareHeaders: ['Stanje', 'Šta predstavlja', 'Potrebna reakcija'],
    compareRows: [['Signal', 'Sirov događaj ili odstupanje.', 'Sačuvati kontekst i proveriti pravilo.'], ['Alert', 'Signal koji je prešao definisan prag.', 'Triage i procena prioriteta.'], ['Incident', 'Potvrđen ili verovatan bezbednosni uticaj.', 'Koordinisana reakcija i sledljiv tok.'], ['Nalaz ranjivosti', 'Potencijalna izloženost koju treba proceniti.', 'Vlasnik, rok i dokaz korekcije.']],
    walkthroughTitle: 'Tok upravljanja ranjivošću',
    walkthroughText: 'Nalaz postaje koristan tek kada se poveže sa stvarnom imovinom i njenom izloženošću. Isti tehnički problem nema isti prioritet na izolovanom razvojnom računaru i na javno dostupnoj usluzi koja obrađuje osetljive podatke.',
    walkthroughPoints: ['Potvrditi da se nalaz odnosi na stvarnu komponentu i aktivnu verziju.', 'Proceni uticaj u kontekstu dostupnosti, podataka i granica poverenja.', 'Odrediti korekciju, kompenzacionu kontrolu ili obrazloženo prihvatanje rizika.', 'Zatvoriti nalaz tek kada postoji dokaz da je izloženost provereno smanjena.'],
    principleTitle: 'Signal traži kontekst',
    principles: ['Prag detekcije treba da ima smisao i razlog, ne samo proizvoljnu brojku.', 'Zatvaranje upozorenja čuva obrazloženje, jer je to znanje za sledeći sličan slučaj.', 'Ranjivost nije rešena promenom statusa, već proverom da je rizik zaista smanjen.'],
    developmentTitle: 'Kako se ova tema vidi u razvoju',
    development: 'Tim bira mali broj signala koji su razumljivi operateru. Za svaki opisuje normalno ponašanje, razlog aktiviranja, odgovornu osobu i bezbedan način provere. Tako se detekcija dizajnira kao proizvodna mogućnost, a ne kao sporedni log.',
    pitfalls: ['Upozorenje bez vlasnika i pravila za triage.', 'Automatsko zatvaranje bez dokaza o rešavanju uzroka.', 'Skeniranje zavisnosti bez odluke kako se nalaz procenjuje i prati.'],
    prompt: 'Koji događaj bi u vašem sistemu bio koristan signal, ali ne i dovoljan dokaz incidenta? Koji kontekst nedostaje?',
    caseTitle: 'Primer: više neuspelih prijava',
    caseText: 'Niz neuspelih prijava može značiti pogrešno zapamćenu lozinku, problem integracije ili pokušaj zloupotrebe. Sam broj neuspeha zato nije dovoljan za zaključak. Triage dodaje kontekst: da li su pokušaji došli sa istog izvora, da li se odnose na osetljive naloge i da li se obrazac nastavlja nakon upozorenja.',
    casePoints: ['Detekcija treba da opiše obrazac koji je vredan pažnje, a ne da svaku grešku proglasi incidentom.', 'Triage čuva odluku i obrazloženje, uključujući razlog zbog kog je upozorenje zatvoreno.', 'Zatvaranje ranjivosti traži dokaz da je izloženost uklonjena ili prihvaćena uz vidljiv preostali rizik.'],
    deepTitle: 'Dizajnerska odluka: signal nije presuda',
    deepText: 'Detekcija pokušava da primeti promenu ponašanja, ne da automatski čita nameru korisnika. Kvalitetan signal zato navodi obrazac, prag i kontekst koji nedostaje za konačnu odluku. Time operater može brzo da razlikuje normalan problem rada sistema od potencijalnog bezbednosnog događaja.',
    deepPoints: ['Prag se bira prema normalnom ponašanju sistema, a ne prema slučajnom broju.', 'Upozorenje ima ozbiljnost, vlasnika i rok do kog se mora pogledati.', 'Incident se otvara kada kontekst pokaže stvarni uticaj ili verovatnu zloupotrebu.'],
    evidenceTitle: 'Učenje nakon događaja',
    evidenceText: 'Dobar post-incident pregled nije potraga za osobom koja je pogrešila. Njegov cilj je da pronađe gde su nedostajali signal, zaštitna provera, jasna odgovornost ili priprema za oporavak. Rezultat treba da menja sistem ili proces na način koji se može proveriti.',
    evidencePoints: ['Hronologija odvaja činjenice od pretpostavki nastalih pod pritiskom.', 'Akcije nakon incidenta imaju vlasnika i proverljiv završetak.', 'Novi scenario se dodaje u testove ili operativne vežbe, kako se isto znanje ne bi izgubilo.'],
  },
  {
    number: 7,
    title: 'Atributi, rizik i periodični pregled pristupa',
    subtitle: 'Kada uloga više nije dovoljna za dobru odluku',
    opening: 'RBAC daje stabilnu osnovu, ali složenije odluke često zavise i od konteksta: pripadnosti, vrste podataka, vremena, stanja resursa ili nivoa rizika. Atributska pravila uvode taj kontekst bez pretvaranja svake moguće kombinacije u novu ulogu.',
    why: 'Risk register i redovan pregled pristupa sprečavaju da se stare odluke pretvore u trajne pretpostavke. Oni čine vidljivim preostali rizik, vlasništvo nad njim i trenutak kada odluku treba preispitati.',
    model: [['Atributi', 'kontekst odluke', 'slate'], ['Politika', 'pravilo koje ih tumači', 'cyan'], ['Rizik', 'uticaj i verovatnoća', 'amber'], ['Pregled', 'potvrda da odluka još važi', 'emerald']],
    schemaTitle: 'Šema kontekstualne odluke',
    schema: [['Pouzdani atributi', 'ko, gde, kada i nad čim', 'slate'], ['Politika', 'pravilo pristupa', 'cyan'], ['Rizik', 'uticaj i preostala izloženost', 'amber'], ['Pregled', 'potvrda ili povlačenje prava', 'emerald']],
    schemaFooter: 'Kontekst daje preciznost odluci, a redovan pregled proverava da li odluka i dalje ima smisla.',
    compareTitle: 'RBAC i ABAC u istoj odluci',
    compareHeaders: ['Pristup', 'Snaga', 'Ograničenje'],
    compareRows: [['RBAC', 'Jasne, stabilne odgovornosti.', 'Teško izražava vreme, vlasništvo i stanje.'], ['ABAC', 'Koristi bogat kontekst odluke.', 'Traži pouzdane atribute i čitljiva pravila.'], ['Kombinacija', 'Uloga daje osnovu, atributi preciziraju.', 'Potrebno je pažljivo objasniti prioritet pravila.'], ['SoD', 'Sprečava rizične kombinacije prava.', 'Mora se proveravati kroz efektivna prava.']],
    walkthroughTitle: 'Od rizika do odluke o prihvatanju',
    walkthroughText: 'Rizik se ne uklanja uvek u potpunosti. Neke mere bi bile preskupe, neke bi zaustavile važan rad, a neke zavise od spoljne strane. Tada je važno da preostali rizik bude vidljiv, obrazložen i vremenski ograničen, a ne zaboravljen.',
    walkthroughPoints: ['Opisati imovinu, scenario i posledicu bez opštih formulacija.', 'Navesti postojeće kontrole i šta one zaista pokrivaju.', 'Oceniti šta ostaje nezaštićeno nakon tih kontrola.', 'Odrediti vlasnika koji prihvata rizik i datum sledećeg pregleda.'],
    principleTitle: 'Pravo pristupa nije zauvek',
    principles: ['Atributi se čitaju iz pouzdanog, jasnog konteksta.', 'Isto stanje mora dovesti do istog rezultata politike.', 'Rizik uključuje imovinu, pretnju, kontrolu i preostalu izloženost.'],
    developmentTitle: 'Kako se ova tema vidi u razvoju',
    development: 'Tim izdvaja odluke koje ne mogu pošteno da stanu u naziv jedne uloge. Zatim ih zapisuje kao pravilo koje se može testirati sa nekoliko suprotnih konteksta. Pregled pristupa proverava da li je nekadašnja poslovna potreba i dalje stvarna.',
    pitfalls: ['Uvođenje atributa bez jasnog izvora i značenja.', 'Pravilo koje zavisi od skrivenog stanja i daje neobjašnjiv rezultat.', 'Konflikt dužnosti otkriven tek nakon što je šteta moguća.'],
    prompt: 'Koju odluku ne biste smeli da zasnivate samo na ulozi i koji dodatni atribut joj daje smisao?',
    caseTitle: 'Primer: ista uloga, različit trenutak',
    caseText: 'Dva operatera imaju istu ulogu, ali jedan radi na incidentu koji mu je dodeljen, dok drugi radi na drugom domenu. Ako politika gleda samo ulogu, obojica bi mogla da odobre istu rizičnu izmenu. Atributi kao što su pripadnost domenu, stanje incidenta i trenutno odobrenje daju odluci kontekst koji naziv uloge sam ne može da nosi.',
    casePoints: ['Atributska odluka ostaje razumljiva samo ako je izvor svakog atributa poznat i pouzdan.', 'Pravilo treba da daje isti rezultat za isti snimak konteksta, kako bi moglo da se testira i objasni.', 'Pregled pristupa vraća tim na pitanje da li pravo i dalje ima poslovni razlog, čak i kada je nekada bilo pravilno dodeljeno.'],
    deepTitle: 'Dizajnerska odluka: kontekst bez haosa',
    deepText: 'Atributi ne treba da postanu skriveni skup izuzetaka koji niko ne razume. Svaki atribut mora imati jasno značenje, izvor i trenutak na koji se odnosi. Politika zatim navodi kako se ti podaci kombinuju, pa odluka može biti ponovljena, testirana i objašnjena bez oslanjanja na intuiciju implementatora.',
    deepPoints: ['Atributi se prikupljaju iz autoritativnih izvora, a ne iz proizvoljnog zahteva klijenta.', 'Pravila treba da budu mala i sastavljena tako da se konflikt može objasniti.', 'Kontekst odluke se beleži dovoljno da kasniji pregled razume rezultat bez čuvanja osetljivih detalja.'],
    evidenceTitle: 'Rizik kao razgovor o odluci',
    evidenceText: 'Risk register nije spisak strašnih scenarija. On daje timu zajednički način da uporedi uticaj, verovatnoću, postojeće kontrole i preostalu izloženost. Kada se rizik prihvati, mora biti jasno ko ga prihvata, zašto i kada će odluka biti ponovo pregledana.',
    evidencePoints: ['Rizik povezuje konkretnu imovinu, pretnju i kontrolu.', 'Pregled pristupa i pregled rizika imaju ritam, vlasnika i očekivani ishod.', 'Segregacija dužnosti sprečava kombinacije prava koje bi jednoj osobi dale preveliku kontrolu.'],
  },
  {
    number: 8,
    title: 'Korelacija događaja, efektivnost kontrola i učenje',
    subtitle: 'Bezbednost kao proces koji se meri i unapređuje',
    opening: 'Završna slika bezbednosti ne sastoji se od pojedinačnih kontrola, već od njihove veze. Događaji dobijaju smisao kada se korelišu, kontrola dobija vrednost kada postoji svež dokaz da radi, a incident postaje prilika da se sistem poboljša bez prikrivanja grešaka.',
    why: 'Merenje efektivnosti sprečava lažni osećaj sigurnosti. Kontrola koja postoji, ali je pogrešno podešena, nikada testirana ili bez vlasnika, ne zaslužuje isto poverenje kao kontrola sa proverljivim dokazom.',
    model: [['Događaji', 'pojedinačni tragovi', 'slate'], ['Korelacija', 'zajednički kontekst', 'cyan'], ['Kontrola', 'smanjuje određeni rizik', 'blue'], ['Dokaz i učenje', 'meri i poboljšava', 'emerald']],
    schemaTitle: 'Šema kontinuiranog unapređivanja bezbednosti',
    schema: [['Događaji', 'tragovi ponašanja sistema', 'slate'], ['Korelacija', 'obrazac i prioritet', 'cyan'], ['Kontrola', 'odgovor na rizik', 'blue'], ['Dokaz i učenje', 'provera i sledeće poboljšanje', 'emerald']],
    schemaFooter: 'Bezbednost napreduje kroz povratnu spregu: dokaz menja razumevanje rizika, a to menja kontrolu.',
    compareTitle: 'Dokaz, pokrivenost i efektivnost',
    compareHeaders: ['Pitanje', 'Slab odgovor', 'Pouzdan odgovor'],
    compareRows: [['Da li kontrola postoji?', 'Klasa ili podešavanje je prisutno.', 'Kontrola ima vlasnika, aktivnu konfiguraciju i svrhu.'], ['Da li radi?', 'Jednom je ručno proverena.', 'Postoji ponovljiv test ili aktuelan operativni dokaz.'], ['Šta pokriva?', 'Pretpostavlja se da važi svuda.', 'Poznati su scenario, granica i izuzeci.'], ['Kako znamo da je oslabila?', 'Problem se vidi tek posle incidenta.', 'Metrika, alert ili redovan pregled otkrivaju odstupanje.']],
    walkthroughTitle: 'Bezbednosna povratna sprega',
    walkthroughText: 'Zreo sistem ne završava bezbednost implementacijom kontrole. Događaji i testovi stvaraju dokaz, dokaz menja procenu rizika, a procena rizika vodi ka boljoj politici ili drugačijoj kontroli. Tako se izbegava lažni osećaj da je jednom završeni posao zauvek dovoljan.',
    walkthroughPoints: ['Događaj ili test otkriva obrazac koji zahteva pažnju.', 'Korelacija povezuje obrazac sa imovinom, akterom i kontrolom.', 'Tim proverava da li postojeća kontrola pokriva stvarni scenario.', 'Nova odluka stvara ažuriranu politiku, test ili operativnu proceduru.'],
    principleTitle: 'Kontrola ima smisao tek uz dokaz',
    principles: ['Korelacija povezuje događaje kroz vreme, aktere i resurse, a ne samo po jednoj poruci loga.', 'Odgovor sa većim posledicama zahteva ljudsku odluku i jasan trag odobrenja.', 'Post-incident pregled ispituje sistem i proces, ne traži najbližeg krivca.'],
    developmentTitle: 'Kako se ova tema vidi u razvoju',
    development: 'Dobra bezbednosna analiza pokazuje uzročnu vezu: koju imovinu štitimo, koji scenario razmatramo, koja kontrola deluje i kako znamo da njeno ponašanje još uvek odgovara nameri. Kratak, jasan dokaz vredi više od duge liste funkcionalnosti.',
    pitfalls: ['Zaključivanje iz jednog događaja bez šireg konteksta.', 'Automatska akcija sa velikom posledicom bez zaštitne provere.', 'Ocena kontrole samo po tome da li je implementirana.'],
    prompt: 'Izaberite jednu kontrolu i pokažite koji rizik ublažava, koji dokaz čuva i kako biste primetili da je prestala da radi.',
    caseTitle: 'Primer: kontrola postoji, ali nema svež dokaz',
    caseText: 'Sistem ima pravilo koje ograničava pristup osetljivom resursu. Pravilo je bilo uspešno testirano pre nekoliko meseci, ali se u međuvremenu promenio model uloga i dodat je novi ulaz u sistem. Bez novog dokaza tim zna da kontrola postoji, ali ne zna da li još pokriva stvarni rizik. Efektivnost zato uključuje svežinu, opseg i rezultat provere.',
    casePoints: ['Korelacija povezuje niz događaja u jednu priču o ponašanju sistema.', 'Mera efektivnosti prati da li kontrola ima vlasnika, dokaz i pokrivenost relevantnog scenarija.', 'Automatizovan odgovor može ubrzati reakciju, ali radnja sa velikom posledicom zadržava ljudsku potvrdu i audit trag.'],
    deepTitle: 'Dizajnerska odluka: korelacija pre zaključka',
    deepText: 'Pojedinačan događaj često ima više mogućih objašnjenja. Korelacija povezuje vreme, aktera, resurs i tok rada, pa tim može da razlikuje slučajnu grešku od obrasca koji zaslužuje reakciju. Cilj nije prikupiti najviše podataka, već povezati one podatke koji menjaju odluku.',
    deepPoints: ['Korelacioni identifikator povezuje nameru, obradu i ishod jedne radnje.', 'Pravila korelacije moraju biti objašnjiva, posebno kada utiču na prioritet upozorenja.', 'Automatizacija predlaže ili ograničava odgovor kada je posledica greške velika.'],
    evidenceTitle: 'Efektivnost je više od postojanja kontrole',
    evidenceText: 'Kontrola može biti implementirana, ali pogrešno podešena, zaobiđena novim tokom ili zastarela posle promene sistema. Zato se njena efektivnost procenjuje kroz dokaz: poslednji uspešan test, pokriveni scenario, vlasnika i sposobnost da se problem primeti ako kontrola zakaže.',
    evidencePoints: ['Dokaz se osvežava kada se promeni relevantan tok, uloga ili granica poverenja.', 'Mera efektivnosti ne skriva nepoznato, već pokazuje gde dokaza nema dovoljno.', 'Kvalitetna analiza povezuje rizik, kontrolu, test i preostalo ograničenje u jednu jasnu priču.'],
  },
]

function pagesFor(topic: Topic): DocumentPage[] {
  return [
    page(`Vežba ${topic.number} — ${topic.title}`, [
      text('h1', `Vežba ${topic.number} — ${topic.title}`),
      text('paragraph', topic.opening),
      text('paragraph', topic.why),
      diagram(topic.subtitle, topic.model, 'Pojmovi su povezani: nijedan od njih sam ne predstavlja kompletnu bezbednosnu odluku.'),
      callout('info', 'Fokus vežbe', 'Cilj je da se razume odluka koju sistem donosi, njen razlog i njen uticaj na zaštitu podataka i usluga.'),
    ]),
    page(`${topic.number}.1. ${topic.principleTitle}`, [
      text('h2', `${topic.number}.1. ${topic.principleTitle}`),
      text('paragraph', topic.why),
      list(topic.principles),
      callout('note', 'Pitanje za diskusiju', topic.prompt),
    ]),
    page(`${topic.number}.2. ${topic.developmentTitle}`, [
      text('h2', `${topic.number}.2. ${topic.developmentTitle}`),
      text('paragraph', topic.development),
      text('h3', 'Česte greške koje treba prepoznati'),
      list(topic.pitfalls),
      callout('success', 'Veza sa ostatkom gradiva', 'Ovaj deo povezuje se sa identitetom, podacima, politikama i dokazima. Istu logiku možete prepoznati u različitim vrstama informacionih sistema.'),
    ]),
    page(`${topic.number}.3. ${topic.caseTitle}`, [
      text('h2', `${topic.number}.3. ${topic.caseTitle}`),
      text('paragraph', topic.caseText),
      list(topic.casePoints),
      callout('note', 'Šta se proverava u dobrom rešenju', 'Rešenje treba da bude razumljivo iz poslovnog konteksta, dosledno primenjeno na serveru i podržano dokazom koji drugi član tima može da ponovi.'),
    ]),
    page(`${topic.number}.4. ${topic.deepTitle}`, [
      text('h2', `${topic.number}.4. ${topic.deepTitle}`),
      text('paragraph', topic.deepText),
      list(topic.deepPoints),
    ]),
    page(`${topic.number}.5. ${topic.evidenceTitle}`, [
      text('h2', `${topic.number}.5. ${topic.evidenceTitle}`),
      text('paragraph', topic.evidenceText),
      list(topic.evidencePoints),
      callout('success', 'Za samostalno proveravanje', 'Pokušajte da za jedan izabrani scenario navedete odluku sistema, podatke koje koristi, očekivani ishod i dokaz kojim drugi član tima može da potvrdi taj ishod.'),
    ]),
    page(`${topic.number}.6. ${topic.schemaTitle}`, [
      text('h2', `${topic.number}.6. ${topic.schemaTitle}`),
      diagram(topic.schemaTitle, topic.schema, topic.schemaFooter),
      text('paragraph', 'Šemu koristite kao kratku proveru razumevanja: za svaki korak trebalo bi da možete da navedete ko ga pokreće, koju odluku donosi i koji trag ostavlja.'),
    ]),
    page(`${topic.number}.7. ${topic.compareTitle}`, [
      text('h2', `${topic.number}.7. ${topic.compareTitle}`),
      table(topic.compareHeaders, topic.compareRows),
      callout('note', 'Kako čitati poređenje', 'Pojmovi nisu zamene jedan za drugi. Svaki rešava drugi deo bezbednosne odluke, pa se njihove uloge dopunjuju.'),
    ]),
    page(`${topic.number}.8. ${topic.walkthroughTitle}`, [
      text('h2', `${topic.number}.8. ${topic.walkthroughTitle}`),
      text('paragraph', topic.walkthroughText),
      list(topic.walkthroughPoints, true),
      callout('success', 'Ključna poruka', 'Cilj nije zapamtiti listu termina, već znati koje pitanje sledeće treba postaviti kada sistem donosi bezbednosno značajnu odluku.'),
      callout('task', 'Rad na vežbi — primena na projekat', `Na dodeljenoj projektnoj celini primeniti princip iz teme „${topic.title}". Identifikovati konkretnu odluku sistema, implementirati je serverski i pripremiti dokaz (test, audit zapis ili demonstraciju) koji tim može da pokaže na projektnoj kontrolnoj tački.`),
    ]),
  ]
}

export const oibThematicExercises = () => topics.flatMap(pagesFor)
